services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    develop:
      watch:
        - action: sync
          path: .
          target: .
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cruddb
      POSTGRES_HOST: postgres
    ports:
      - "5001:5000"
    develop:
      watch:
        - action: rebuild
          path: .
          target: .
          ignore:
            - node_modules/
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cruddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: